#!/usr/bin/env php
<?php
/**
 * This file is part of Notadd.
 * @author TwilRoad <269044570@qq.com>
 * @copyright (c) 2016, iBenchu.org
 * @datetime 2016-09-02 18:48
 */
 define('NOTADD_START', microtime(true));
 require 'vendor/autoload.php';
(new \Notadd\Foundation\Console\Server(__DIR__))->listen();